[package]
name = "syle-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid = { version = "1", features = ["serde", "v4", "js"] }

[dev-dependencies]
uuid = { version = "1", features = ["serde", "v4"] }
